name: docker build on pr
run-name: Build & Test PR (${{ github.event.client_payload.detail.pull_request }})
on:
  repository_dispatch:
    types:
      - pr-trigger

permissions: {}

# A push via dependabot basically means that the github actions
# have been upgraded; just make sure that the docker build works
# but don't push a new image.
jobs:
  docker_build:
    uses: ./.github/workflows/docker-build-image.yml
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
      issues: write
      statuses: write
    with:
      registry_push: false
      target_branch: ${{ github.event.client_payload.base.ref }}
      sha: ${{ github.event.client_payload.base.sha }}
      pull_request: ${{ github.event.client_payload.detail.pull_request }}

  check-pr:
    needs:
      - docker_build
    if: |
      github.event_name == 'pull_request'
    uses: quotidian-ennui/workflows-olio/.github/workflows/check-pr-with-trigger.yml@main
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
      checks: write
