name: pr-trigger
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  dependabot-build-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    name: PR Trigger
    steps:
      - name: dispatch
        uses: quotidian-ennui/actions-olio/pr-trigger@370d322048e3996c58a5ec88e9e2461919092c40 # v1.0.0
