name: pr-trigger
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  dependabot-build-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    name: PR Trigger
    steps:
      - name: dispatch
        uses: quotidian-ennui/actions-olio/pr-trigger@83871db203c510c8c8d65292f24ebf5437728e7c # v0.9.1
